## This file is a template remove the .template to use the file

libraries:                                      # Library mappings must have a colon (:) placed after them
  Series:
    metadata_path:
    - file: config/returning-soon.yml # this is the yml that pulls the returning soon list from your trakt account.
    overlay_path:
    - remove_overlays: false
    - file: config/overlays/returning-soon-overlay.yml # this doesn't exist until the first run.


