## EXAMPLE SETUP FOR YAML ##

libraries:                                      # Library mappings must have a colon (:) placed after them
  Series:            # <-- sample library name. Your's does not have to be the same. This is what you would enter into preferences/settings.yml
    metadata_path:
    - file: config/returning-soon.yml # this is the yml that pulls the returning soon list from your trakt account.
    overlay_path:
    - remove_overlays: false
    - file: config/overlays/returning-soon-overlay.yml # this doesn't exist until the first run.


