collections:
  Returning Soon:
    trakt_list: https://trakt.tv/users/YOUR_USERNAME/lists/returning-soon
    collection_order: custom
    visible_home: true
    visible_shared: true
    sync_mode: sync
# make sure to fill-in your username #
# add this as a series overlay file #
# nothing else to do in here #