##
##
##
templates:
  # TEXT CENTER
  TV_Top_TextCenter:
    sync_mode: sync
    builder_level: show
    overlay:
      name: text(<<text>>)
      horizontal_offset: 0
      horizontal_align: center
      vertical_offset: 0
      vertical_align: top
      font: config/fonts/Juventus-Fans-Bold.ttf
      font_size: 70
      font_color: <<color>>
      group: TV_Top_TextCenter
      weight: <<weight>>
      back_color: <<back_color>>
      back_width: 1920
      back_height: 90
#      back_align: top
#      back_padding: 20
##
##
##

overlays:
  # NEW
  TV_Top_TextCenter_New:
    template:
      - name: TV_Top_TextCenter
        weight: 60
        text: "N E W  S E R I E S"
        color: "#FFFFFF" # white
        back_color: "#008001"
    plex_all: true
    filters:
      tmdb_status:
        - returning
        - planned
        - production
      first_episode_aired: 45


#### These are commented out as the SERIES OVERLAY RETURNING SCRIPT generates the entries with dynamic dates.
  # Airing
#  TV_Top_TextCenter_OnAir:
#    template:
#      - name: TV_Top_TextCenter
#        weight: 40
#        text: "A I R I N G"
#        color: "#FFFFFF" # white
#        back_color: "#343399"
    #plex_all: true
#    tmdb_discover:
#      air_date.lte: today
#    filters:
#      tmdb_status:
#        - returning
#        - planned
#        - production
#      last_episode_aired: 15

  # RETURNING
#  TV_Top_TextCenter_Returning:
#    template:
#      - name: TV_Top_TextCenter
#        weight: 30
#        text: "R E T U R N I N G"
#        color: "#FFFFFF"
#        back_color: "#81007F"
#    plex_all: true
#    filters:
#      tmdb_status:
#        - returning
#        - planned
#        - production


  # ENDED
  TV_Top_TextCenter_Ended:
    template:
      - name: TV_Top_TextCenter
        weight: 20
        text: "E N D E D"
        color: "#FFFFFF" # white
        back_color: "#000000"
    plex_all: true
    filters:
      tmdb_status:
        - ended

  # Canceled
  TV_Top_TextCenter_Canceled:
    template:
      - name: TV_Top_TextCenter
        weight: 20
        text: "C A N C E L E D"
        color: "#FFFFFF" # white
        back_color: "#CF142B"
    plex_all: true
    filters:
      tmdb_status:
        - canceled
